version: '3.1'

services:

  signup-db:
    build:
      context: ../docker/sql-server

  signup-web:
    build:
      context: ..
      dockerfile: ./docker/frontend-web/Dockerfile

  homepage:
    build:
      context: ..
      dockerfile: ./docker/frontend-reverse-proxy/homepage/Dockerfile

  proxy:
    build:
      context: ..
      dockerfile: ./docker/frontend-reverse-proxy/reverse-proxy/Dockerfile

  message-queue:
    build:
      context: ..
      dockerfile: ./docker/backend-async-messaging/message-queue/Dockerfile

  reference-data-api:
    build:
      context: ..
      dockerfile: ./docker/backend-rest-api/reference-data-api/Dockerfile

  signup-save-handler:
    build:
      context: ..
      dockerfile: ./docker/backend-async-messaging/save-handler/Dockerfile

  signup-index-handler:
    build:
      context: ..
      dockerfile: ./docker/backend-analytics/index-handler/Dockerfile    

  prometheus:
    build:
      context: ..
      dockerfile: ./docker/metrics-dashboard/prometheus/Dockerfile

  grafana:
    build:
      context: ..
      dockerfile: ./docker/metrics-dashboard/grafana/Dockerfile  